apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react-app-namespace
  labels:
    app: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: akhilkumar119/react-app:v1
        ports:
        - containerPort: 3000
          protocol: TCP
